name: Go Lint
on:
  push:
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.28.3