on: [push, pull_request]
name: Go Tests
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...